services:
  web:
    image: ${FULL_IMAGE}
    container_name: ${IMAGE}  # Replace / with - for container name
    build:
      context: .
    ports:
      - "8080:8080"
    stdin_open: true   # equivalent to -it
    tty: true          # equivalent to -it
    restart: unless-stopped
